### ISSUE TITLE
Failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [defaultxr/bdef#1]
Building with SBCL 2.0.9.5-442f54894 / ASDF 3.3.1 for quicklisp dist creation.

Commit id 954ed510ee412db41d3fc4bd328bb21e7d9513d0

*bdef/incudine* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A50103}>: Component #:INCUDINE not found, required by #<SYSTEM "bdef/incudine">

```

[Full log here](http://report.quicklisp.org/2020-10-06/failure-report/bdef.html)

**Comment by defaultxr** [comment]
I thought you skip systems with missing dependencies? Incudine is not in Quicklisp, so it is expected that the `bdef/incudine` sub-system will not build unless Incudine is manually included in one's `local-projects` directory.

The same is true for https://github.com/defaultxr/cl-patterns/issues/10 ; these failures are caused by systems not yet in Quicklisp, which need to be downloaded manually.

If missing dependencies now cause failures in Quicklisp, is there a way to denote a system as an "expected failure" or otherwise have Quicklisp ignore it? Do these kinds of systems need to be moved out to their own separate `.asd` file?

**Comment by quicklisp** [comment]
I do skip those systems. Sorry for the misleading title - only the systems
that fail are excluded, not the whole project.

Should I add the missing projects to Quicklisp, or exclude the failing
systems for now?

**Comment by defaultxr** [comment]
For now I think it would be best to just exclude the failing systems for `bdef` and `cl-patterns`, as I'm not sure the `cl-alsaseq` dependency would meet all of Quicklisp's requirements yet (I haven't checked, it might throw warnings).

I'm also not really involved in the development of `incudine`, I just depend on it, so I can't really say anything about if that one is Quicklisp-ready, or if the author is even interested in it being on Quicklisp.

**Comment by quicklisp** [comment]
Thanks, I'll excluded these systems from builds and build failure reports.
